config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments 
  has_many :students, through: :enrollments

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course 
end

app/models/horse.rb
class Horse

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :addresses
  has_many :enrollments
  has_many :courses, through: :enrollments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<h1>All Courses</h1>
<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to course.name, course_path(course)%>
    </li>
  <% end %>
</ul>

app/views/courses/show.html.erb
  <h2><%= @course.name %><br></h2>

  <br>
  <% @course.students.each do |student| %>
  <%= student.name %><br>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBasicsChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>All Students</h1>
<ul>
  <% @students.each do |student| %>
    <li>
      <%= link_to student.name, student_path(student)%>
    </li>
  <% end %>
</ul>

app/views/students/show.html.erb
  <h2><%= @student.name %>'s Information</h2>

  <% @student.addresses.each do |address| %>
    <%= address.street %><br>
    <%= address.city %>, <%= address.state %>
    <%= address.zip %><br>
    <br>
  <% end %>
  <h2><%= @student.name %>'s Courses</h2>
  <% @student.courses.each do |course| %>
    <%= link_to course.name, course_path(course)%><br>
    <br>
  <% end %>